# Generated by Django 3.2.9 on 2021-12-06 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(default='', max_length=50)),
                ('rate', models.FloatField(default=0.0)),
                ('add_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 20, 7, 2, 626373))),
            ],
        ),
    ]
