# Generated by Django 3.2.9 on 2021-12-08 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 8, 15, 57, 37, 861447)),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
