# Generated by Django 3.2.9 on 2021-12-08 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_auto_20211208_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 8, 16, 22, 6, 106239)),
        ),
    ]
