# Generated by Django 3.2.9 on 2021-12-09 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20211209_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 9, 14, 7, 52, 284131)),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
