# Generated by Django 3.2.9 on 2021-12-09 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20211209_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 9, 15, 35, 53, 251913)),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
