# Generated by Django 3.2.9 on 2021-12-10 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20211209_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 17, 57, 3, 660635)),
        ),
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
